config/routes.rb
Rails.application.routes.draw do
  get 'portfolio/index'
  resources :tv_dbs
  root 'tv_dbs#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tv_db.rb
class TvDb < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tv_dbs_controller.rb
class TvDbsController < ApplicationController
  before_action :set_tv_db, only: [:show, :edit, :update, :destroy]

  # GET /tv_dbs
  # GET /tv_dbs.json
  def index
    @tv_dbs = TvDb.all
  end

  # GET /tv_dbs/1
  # GET /tv_dbs/1.json
  def show
  end

  # GET /tv_dbs/new
  def new
    @tv_db = TvDb.new
  end

  # GET /tv_dbs/1/edit
  def edit
  end

  # POST /tv_dbs
  # POST /tv_dbs.json
  def create
    @tv_db = TvDb.new(tv_db_params)

    respond_to do |format|
      if @tv_db.save
        format.html { redirect_to @tv_db, notice: 'Tv db was successfully created.' }
        format.json { render :show, status: :created, location: @tv_db }
      else
        format.html { render :new }
        format.json { render json: @tv_db.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tv_dbs/1
  # PATCH/PUT /tv_dbs/1.json
  def update
    respond_to do |format|
      if @tv_db.update(tv_db_params)
        format.html { redirect_to @tv_db, notice: 'Tv db was successfully updated.' }
        format.json { render :show, status: :ok, location: @tv_db }
      else
        format.html { render :edit }
        format.json { render json: @tv_db.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tv_dbs/1
  # DELETE /tv_dbs/1.json
  def destroy
    @tv_db.destroy
    respond_to do |format|
      format.html { redirect_to tv_dbs_url, notice: 'Tv db was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tv_db
      @tv_db = TvDb.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tv_db_params
      params.require(:tv_db).permit(:name, :desc, :number_of_episodes, :up_to_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tv_dbs_helper.rb
module TvDbsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TvDatabase</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tv_dbs/_form.html.erb
<%= form_with(model: tv_db, local: true) do |form| %>
<div class="form-group">
  <% if tv_db.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tv_db.errors.count, "error") %> prohibited this tv_db from being saved:</h2>

      <ul>
      <% tv_db.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_field :desc %>
  </div>

  <div class="field">
    <%= form.label :number_of_episodes %>
    <%= form.number_field :number_of_episodes %>
  </div>

  <div class="field">
    <%= form.label :up_to_date %>
    <%= form.text_field :up_to_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
  </div>
<% end %>

app/views/tv_dbs/edit.html.erb
<div class="container">
  <h1>Editing Show</h1>

  <%= render 'form', tv_db: @tv_db %>

  <%= link_to 'Back To Show', @tv_db %> |
  <%= link_to 'Back to Show List', tv_dbs_path %>
</div>

app/views/tv_dbs/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>TV Shows</h1>

<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Description</th>
      <th scope="col">Episodes</th>
      <th scope="col">Up to date</th>
    </tr>
  </thead>

  <tbody>
    <% @tv_dbs.each do |tv_db| %>
      <tr>
        
        <td scope="row"><%= link_to tv_db.name , tv_db %></td>
        <td scope="row"><%= tv_db.desc %></td>
        <td scope="row"><%= tv_db.number_of_episodes %></td>
        <td scope="row"><%= tv_db.up_to_date %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add new', new_tv_db_path %>
</div> 

app/views/tv_dbs/new.html.erb
<div class="container">
<h1>New Tv Db</h1>

<div class="form-group">

<%= render 'form', tv_db: @tv_db %>
</div>

<%= link_to 'Back', tv_dbs_path %>
</div>

app/views/tv_dbs/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong><br>
    <%= @tv_db.name %>
  </p>

  <p>
    <strong>Description:</strong><br>
    <%= @tv_db.desc %>
  </p>

  <p>
    <strong>Number of episodes:</strong><br>
    <%= @tv_db.number_of_episodes %>
  </p>

  <p>
    <strong>Up to date:</strong><br>
    <%= @tv_db.up_to_date %>
  </p>


  <%= link_to 'Edit', edit_tv_db_path(@tv_db) %> |
  <%= link_to 'Delete', @tv_db, method: :delete, data: { confirm: 'Are you sure?' } %> |
  <%= link_to 'Back', tv_dbs_path %>

</div>